### PR TITLE
Long Time No Merge

### PR DESCRIPTION
**Pull request by clochix**

### CODE REVIEW

**Comment by aenario** [comment]
Quick review, nothing to say on code style.
Please brunch b && cake build so I can test in a true VM

**Comment by aenario** [comment]
fix #104 OK
fix #64 OK
fix #67 OK
fix #98 OK
fix #95 OK
fix #97 OK
fix #92 OK (a bit rash, but it makes sense)
fix #88 OK
fix #105 OK

#96 KO  : I didn't manage to get a Notification to show, might be caused by chrome. Good to merge anyway !

**Comment by aenario** [comment]
Please build your last change

**Comment by aenario** [comment]
build & testfix for server-side on aenario/master, waiting for travis
https://travis-ci.org/aenario/cozy-emails/builds/47532690

I did not manage to run client tests on my VM, do they work on your computer ?

**Comment by clochix** [comment]
Client tests work fine here, could you give me the error log ?

**Comment by aenario** [comment]
Ok, tested on my cozy and everything seems to work. 
The error log was similar to travis (breaking from the start), we should arrange a pair-programming session smetime this weel, may be we can figure out what's preventing them to run on travis !

**Comment by frankrousseau** [comment]
+1 for the pair programming :)

**Pull request merged**
