### PR TITLE
Ui: layouts

### PR DESCRIPTION
**Pull request by m4dz**
Currently WIP, this PR present the base of flex-layouts. At this time, styles are completely disabled on menu and messages-list, and lack paddings in panes (as well as comments). Interactions are OK, so you can review / test it to check if some features are broken due to my huge-source-code-axe.

Now it's time for painting (: just call me Valerie Damim4dz :)!

### CODE REVIEW

**Comment by frankrousseau** [comment]
It's hard to discuss it because the removed style on the left panel and the menu make it really ugly ;).

I'm not sure we should put back animation when a panel moves. We discussed it already and decided to remove the animation.

**Comment by m4dz** [comment]
> It's hard to discuss it because the removed styles on the left panel and the menu make it really ugly ;).

Yep, currently, it's all but ready to use :laughing:. I'm hardly working on style to restore a clean Ui. I've early release the PR to get comments on the React part of the code, cause I' unsure to do things the right way and I'm aware about any kind of improvements…

I was not aware of that

> I'm not sure we should put back animation when a panel moves. We discussed it already and decided to remove the animation.

Give them a chance, pleeeease :smile:… As I told to @Benibur yesterday, I'll never release something just because it's beautiful. It must be useful or it will not be. So If it's relevant for UX when styles come back, I will submit them to the vote (instead, I'll remove it myself with pleasure).

panel animation using CSS

**Comment by frankrousseau** [comment]
Ok. Can't wait to see the result.

**Comment by m4dz** [comment]
Whouhouhou! Big Pressure 😄!

**Comment by clochix** [comment]
I did a rapid review, saw nothing too ugly, so I think we can merge this first step.

**Comment by frankrousseau** [comment]
Thx @clochix for the review. Thx Matthias for the PR.

**Comment by m4dz** [comment]
Many thanks to all of you! Let's go to fix the bugs and improve,now :smile:!

**Pull request merged**
