### PR TITLE
Add Lodash to client dependencies and use includes instead of contains

### PR DESCRIPTION
**Pull request by frankrousseau**

### CODE REVIEW

**Comment by misstick** [comment]
What the aim of this PR : FIX the build? Will you FIX all this https://github.com/lodash/lodash/wiki/Deprecations or shall we do it in an other PR?

**Comment by frankrousseau** [comment]
@misstick the goal is to fix the build.

**Comment by misstick** [comment]
@frankrousseau : Is you PR finished and ready to merge? What about other `may break the build` cases listed about `lodash v4.0.0` depreciated ?

**Comment by frankrousseau** [comment]
I think it's ready to merge, I'm going to check if there are other problems.

**Comment by frankrousseau** [comment]
Without this PR, the app doesn't work at all.

**Comment by frankrousseau** [comment]
I searched for deprecated function calls and I didn't find one except the ones fixed by this PR.

**Comment by misstick** [comment]
👍

**Pull request merged**
