### PR TITLE
Changed: refresh button doesn't do anything (for now).

### PR DESCRIPTION
**Pull request by jsilvestre**
@Benibur suggested we don't show at all the imap refresh to the user, because it's hard to it right (if you want details on why, call me it's be quicker). Instead, we refresh the client (browser)'s cache with server's data.

Since it's already done throught realtime, I made the button...do nothing. If that works better, we could improve in that direction later on, but today is release day, so this is more a quickfix than anything else.

### CODE REVIEW

**Comment by clochix** [comment]
Looks good to me, that's waht we discussed on IRC. Thanks @jsilvestre ☺

**Comment by frankrousseau** [comment]
Not so good, I can't read my emails anymore.

**Comment by frankrousseau** [comment]
(on my second account).

**Comment by clochix** [comment]
We need to merge quickly, to test and find bugs. My latest PR contains bugfixes for problems I got after the previous merges.

**Pull request merged**
