### PR TITLE
Improve reply experience

### PR DESCRIPTION
**Pull request by frankrousseau**
* Remove empty line at the beginning
* Change displayed date as reply introduction
* Add a style to blockquotes

### CODE REVIEW

**Comment by aenario** [comment]
@clochix , you know this part better, please review.

**Comment by clochix** [comment]
Seems good to merge ☺

**Comment by aenario** [comment]
Thanks @frankrousseau for PR & @clochix for review.
Note : coffeescript multiline strings allows you to start at any indentation. You dont need to break the file structure. I made that change in https://github.com/cozy/cozy-emails/commit/f1622132951fecad936dc97412862619a2a1fc53

Still trying to figure out where frank's bug might come from.

**Comment by frankrousseau** [comment]
I prefer to break indentation in tha case, mainly for the 80 chars limit. Whatver it's matter of taste.

**Pull request merged**
