### PR TITLE
Move Utils into Getters

### PR DESCRIPTION
**Pull request by misstick**
- [x] remove dead code,
 - [x] remove useless `mixin` (ie. un-used or called once),
 - [x] remove useless `utils` (ie. un-used or called once),
 - [x] remove  `stores` calls into `components`,
 - [x] move `utils` into `libs`

### CODE REVIEW

**Comment by m4dz** [comment]
Ok for me. @misstick can you rebase on `development`? Thanks!

**Comment by misstick** [comment]
@m4dz : dont forget to look PR labels : this PR is not finished yep :)

**Comment by m4dz** [comment]
> dont forget to look PR labels

oops, you've assigned me, I've presumed that the PR was ready. Thanks to remind me ;)

**Comment by frankrousseau** [comment]
I propose you to merge this one directly. It's too hard to review it properly (too many changes).

**Comment by m4dz** [comment]
@misstick why have you move performance mesurement and reporting initilializers to NotificationActionCreator?

**Comment by misstick** [comment]
@m4dz : because the test made about perf produce notifications as well as reporting; not a good idea?

**Comment by misstick** [comment]
@frankrousseau: this PR is about moving a lot of files so it is about architecture cleansing; even if there are a lot of changes, I'd like to know if the moves are OK

**Comment by m4dz** [comment]
Hmm, I don't think so: reporting, realtime, performance… are parts of the whole app, used everywhere, and I think they must belongs on their own parts (libs?) and not lost in another component.

**Pull request merged**
