### PR TITLE
Message Action Fixes

### PR DESCRIPTION
**Pull request by aenario**
Replace the message-by-message logic with mailbox-by-mailbox and
messages batching. Also correct some logic error with handling of
message in weird states (trash + other box).

### CODE REVIEW

**Comment by aenario** [comment]
Testing on my cozy right now and I still have some bugs. Please dont merge.

**Comment by aenario** [comment]
Actually, the bugs are "only" display and realtime issues and will be solved during this sprint. Good to merge & publish as-is. @poupotte , could you install & review that version ?

**Comment by poupotte** [comment]
Actions as deletion or mark as read work well for me. However, filters don't work well. Indeed, messages displayed after a selection or an unselection don't always correspond to the filter but I'm not sure if this issue is due to this PR.

**Comment by frankrousseau** [comment]
ok let's merge it.

**Pull request merged**
