### PR TITLE
Add unit tests to client (do not merge)

### PR DESCRIPTION
**Pull request by frankrousseau**
First attempt to add unit tests on the client side. It works nice with the `jsdom` library. But brunch messes up with require, so we can't use it right now (require are runned even if they should not be executed).

That's something the Brunch team is working on. So at some point we can expect it will be solved.

Any ideas to fix this problem are welcome.

### CODE REVIEW

**Comment by jsilvestre** [comment]
I can't wait we can use browserify with Brunch, that would make things much cleaner.

**Comment by frankrousseau** [comment]
Good points @jsilvestre. There is a plugin called brunch-browserify. Do you know it?

**Comment by jsilvestre** [comment]
Yes, but it has serious limitations. Browserify support should be native in the next major version of Brunch, I must take some times to try it out.

**Comment by frankrousseau** [comment]
About jsdom the 3.x version requires more configuration and is not maintained anymore. So, I prefer to use the latest one.

**Comment by jsilvestre** [comment]
That gives me a good reason to install io.js ;-) It's easy to do with https://github.com/tj/n

**Comment by frankrousseau** [comment]
I close this one. We'll work on it when Brunch will be ready.

**Pull request closed without merging**
