### PR TITLE
Advanced SMTP Parameters, expunge trash and minor bugfixes

### PR DESCRIPTION
**Pull request by clochix**
@aenario could you have a look at the server side part of trash expunge ? Thanks !

### CODE REVIEW

**Comment by aenario** [comment]
code-wise, everything LGTM :+1: 

Client tests are still red. Is this expected ?
Please build so it can be merged directly.

**Comment by aenario** [comment]
I am way too happy about this, so congrats @clochix on green tests !

**Comment by aenario** [comment]
Question @frankrousseau : 
As a TR for this repo, should I : 
A - install the new version in my cozy to check it dont break
B - install the new version in my cozy to check it actually fix issues
C - dont install the new application and just review code quality
D - la réponse D

**Comment by frankrousseau** [comment]
A for sure. B is not mandatory but double checking fixes is always good.

**Pull request merged**
