### PR TITLE
Clean Mailbox Menu

### PR DESCRIPTION
**Pull request by misstick**
- [x] fix `depth` issues,
 - [x] do not display mailbox with tags `\Noselect`,
 - [x] remove `settingsButton`,
 - [x] remove `dragEvents` on `mailboxLinks`.
 - [x] remove `expungeMailbox` (have to be fixed),
 - [x] remove `editAccountLink` (this page has to be fixed).

### CODE REVIEW

**Comment by misstick** [comment]
@m4dz : PR https://github.com/cozy/cozy-emails/pull/842 need to be merged before

**Comment by frankrousseau** [comment]
It's the end of the sprint. Can I merge that one?

**Comment by m4dz** [comment]
Yes @frankrousseau : between my whole work on #839, some help to my colleagues, my family, and the rest of my life, I can take the time in my evenings to make reviews and merges, don't worry…

**Comment by frankrousseau** [comment]
Sorry, it's not what I meant. I was just asking if I could handle it or not.

**Comment by m4dz** [comment]
Yup, no problem, I've already planned to review them since children asleep ;). Have a bad trip since too many weeks, and my reply was a little bit abrupt, I'm sorry. Anyway, I'll be happy to make a retrospective after we close the milestone :).

**Pull request merged**
