### PR TITLE
Move build process to npm scripts

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by m4dz** [comment]
Dear friends (@aenario, @nono, @poupotte), I gently ask for your opinions about this one :smile:

**Comment by nono** [comment]
- It's nice to have a clean like this!
- You should update the README
- Travis build is red
- the tx step for npm run build should be optional
- Why did you delete everything in build if it's not ignored by git? To check the build on travis?

**Comment by m4dz** [comment]
> You should update the README

Yup, good idea :)

> Travis build is red

I'm currently checking with Travis how to properly handle the build on its side

> the tx step for npm run build should be optional

Nice! Any idea how to do this? (using `npm run build -- --with-locales` ?)

> Why did you delete everything in build if it's not ignored by git? To check the build on travis?

Exactly :). And because we initialy plan to let Travis make the build himself and push it to the master branch (not sure how to correctly address this one, need more discuss about it)

**Comment by nono** [comment]
For tx, maybe just:

```js
"tx": "tx pull --all || true",
```

**Comment by m4dz** [comment]
Yeah, just saw it, thanks :+1:

**Comment by jsilvestre** [comment]
>   > Why did you delete everything in build if it's not ignored by git? To check the build on travis?

> Exactly :). And because we initialy plan to let Travis make the build himself and push it to the master branch (not sure how to correctly address this one, need more discuss about it)

**Comment by nono** [comment]
@m4dz and we can put `travis_retry` before `npm install`. It can avoid some network errors. https://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/

**Comment by nono** [comment]
In `.travis.yml`, there is a `git clone git://github.com/mycozycloud/cozy-data-system.git`. We should update the URL to git://github.com/cozy/cozy-data-system.git

**Comment by m4dz** [comment]
I've removed the `^` marker, but I ask myself about the need to fix versionning on devDependencies (which normally are only used in a controlled environment where errors can be easily detected).

**Comment by frankrousseau** [comment]
Thank you @m4dz. Our experience of letting the `^` is a lot of time wasted because of it (everyone doesn't share the same code base of it). It's simpler to remove it all time.

**Pull request merged**
