### PR TITLE
Fix account creation

### PR DESCRIPTION
**Pull request by clochix**

### CODE REVIEW

**Comment by frankrousseau** [comment]
Be careful you merge a PR without commits.

**Comment by clochix** [comment]
Don't know what happened, my PR was made of 4 or 5 commits.

**Comment by aenario** [comment]
I dont know what happened .... Commits log for later references.
https://github.com/cozy/cozy-emails/compare/38c9140...fd264b4

**Comment by clochix** [comment]
And the commits messages, for the refs to original tickets
 - Fix display of errors on Account creation
 - Allow IMAP login distinct from the address, refs #84
 - Fix JS error on account creation
 - Fix account parameters check
 - Add spinner on account check button, refs #340

**Pull request merged**
