### PR TITLE
Prevent application to crash when there is no account

### PR DESCRIPTION
**Pull request by gregorylegarec**
On my first launch, Emails crashed with an error related to undefined account. This PR fixes this issue.

I still have unit tests to write (I am currently looking at existing tests)

@misstick please review, or assign someone else. :)

### CODE REVIEW

**Comment by misstick** [comment]
Hi @gregorylegarec can you answer this question to add context for this PR plz?
- what is it for? (you can fil description with the purpose or issue this PR is about), 
- Have you finished (cf `labels`)?
 - Are you waiting for review?
 - from who (cf `assignees`)?

**Comment by misstick** [comment]
You can look at my FIX here https://github.com/cozy/cozy-emails/pull/898/files#diff-640eb3029fcfa6ff4c6ac76d37ffa86cL507

This test doesnt actually exist but will in PR above; don't lose time looking at a test that doesnt exist :)

**Comment by misstick** [comment]
@gregorylegarec: I think this PR is useless because of https://github.com/cozy/cozy-emails/pull/898 Sorrryyyyyy :(

I can check I may be wrong

**Comment by gregorylegarec** [comment]
Yep it seems that you're right.

No problem for me.

**Pull request closed without merging**
