### PR TITLE
Change level log on info

### PR DESCRIPTION
**Pull request by poupotte**

### CODE REVIEW

**Comment by clochix** [comment]
♥♥♥♥

**Comment by misstick** [comment]
@poupotte : it seems that this change break existing tests :(

**Comment by poupotte** [comment]
Actually, tests are broken on [master branch](https://travis-ci.org/cozy/cozy-emails/jobs/121097353) .

**Comment by frankrousseau** [comment]
@misstick I know tests are red but if you check the changes, it looks ok. Maybe @poupotte that you can put a condition to switch between log levels depending on the environment.

**Pull request merged**
