### PR TITLE
[fix] Gmail mailboxes issues 

### PR DESCRIPTION
**Pull request by misstick**
- [x] Inbox belongs to `flaggedMailbox`; it should appear on top of mailboxes list,
- [x] Inbox isnt found for gmail accounts,
- [x] spinner is always visible into `[Gmail]` mailbox,
- [x] special mailbox icons are not found (`drafts`, `deletedMessages`, etc.).

### CODE REVIEW

**Comment by misstick** [comment]
@aenario: I found that gmailInbox isnot flagged as it should; `mailbox.tree` is not the same as OVH, ie. We have to look at `mailbox.attribs` instead. Did you know it? I'd love you tell me that long story :)

**Comment by misstick** [comment]
@m4dz : can you review this PR; its quite old and finished :(

**Comment by frankrousseau** [comment]
ping @aenario Can you help on some emails review?

**Comment by m4dz** [comment]
I'm on it (sorry for the delay :/)

**Comment by aenario** [comment]
@misstick If i recall correctly, the idea is that we should trust mailbox.attribs when possible.

However, 
- some providers dont have attribs to their mailboxes at all, so we attempt to guess by the name.
- in some cases (like every cozy team member who switched from gmail to OVH), the hierarchy is weird (INBOX > INBOX / INBOX > Sent), see tests fixtures. This was an attempt to have the displayed tree cleaner in these cases.

**Comment by m4dz** [comment]
Thanks :tada: ! (and again, sorry for the delay)

**Pull request merged**
